services:
  db:
    image: mongo:7.0
    container_name: t20_db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  api:
    build: ./app
    container_name: t20_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/tormenta20
    volumes:
      - ./app:/app

  web:
    build: ./frontend
    container_name: t20_web
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # <--- ESSA LINHA SALVA O SEU VITE!
    environment:
      - VITE_API_URL=http://localhost:8000
