# --- ESTRUTURA PARA DADOS DE ORIGENS (T20 JdA) ---
# itens: String com a descrição dos itens iniciais.
# beneficios_lista: Lista de todos os benefícios (perícias e poderes) que o jogador PODE escolher.
# pericias_fixas: Lista de perícias que a origem concede e são consideradas como 'escolhidas'.
# qtd_escolhas: Quantidade de benefícios totais que o jogador escolhe (padrão é 2).

DADOS_ORIGENS = {
    "Acólito": {
        "descricao": "Você ingressou cedo em alguma ordem religiosa, tendo lembranças carregadas de orações, evangelhos e ensinamentos.",
        "itens": "Símbolo sagrado, traje de sacerdote.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Cura", "Religião", "Vontade", "Medicina", "Membro da Igreja", "Vontade de Ferro"],
    },
    "Amigo dos Animais": {
        "descricao": "Desde criança você tem facilidade em lidar com animais, sempre conversou com eles e sentiu ser capaz de compreendê-los.",
        "itens": "Cão de caça, cavalo, pônei ou trobo (escolha um).",
        "qtd_escolhas": 2,
        "pericias_fixas": ["Adestramento", "Cavalgar"],
        "beneficios_lista": ["Amigo Especial"],
    },
    "Amnésico": {
        "descricao": "Você perdeu a maior parte da memória. Tem apenas uma intuição sobre aquilo que consegue fazer. Seus atuais companheiros são a única família que conhece.",
        "itens": "Um ou mais itens (somando até T$ 500), aprovados pelo mestre, que podem ser uma pista misteriosa do seu passado.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Lembranças Graduais"],
    },
    "Aristocrata": {
        "descricao": "Você nasceu na nobreza e recebeu educação sofisticada. Luta para conciliar as expectativas da família com a vida de aventuras?",
        "itens": "Joia de família no valor de T$ 300, traje da corte.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Diplomacia", "Enganação", "Nobreza", "Comandar", "Sangue Azul"],
    },
    "Artesão": {
        "descricao": "Você foi treinado por um parente, mestre ou guilda para fabricar itens importantes no mundo civilizado.",
        "itens": "Instrumentos de ofício (qualquer), um item que você possa fabricar de até T$ 50.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Ofício", "Vontade", "Frutos do Trabalho", "Sortudo"],
    },
    "Artista": {
        "descricao": "Você possui talento e produz entretenimento. Talvez saiba entoar belas canções ou seja um ator/dançarino formado.",
        "itens": "Estojo de disfarces ou um instrumento musical a sua escolha.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Atuação", "Enganação", "Atraente", "Dom Artístico", "Sortudo", "Torcida"],
    },
    "Assistente de Laboratório": {
        "descricao": "Você atuou como ajudante para um alquimista, inventor ou mago, exposto a experimentos perigosos.",
        "itens": "Instrumentos de Ofício (alquimista).",
        "qtd_escolhas": 2,
        "pericias_fixas": ["Ofício", "Misticismo"],
        "beneficios_lista": ["Esse Cheiro...", "Venefício", "Poder da Tormenta (Escolha)"],
    },
    "Batedor": {
        "descricao": "Você aprendeu a achar caminhos e dirigir outros com segurança, seja conduzindo caravanas ou rastreando inimigos.",
        "itens": "Barraca, equipamento de viagem, uma arma simples ou marcial de ataque à distância.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Furtividade", "Percepção", "Sobrevivência", "À Prova de Tudo", "Estilo de Disparo", "Sentidos Aguçados"],
    },
    "Capanga": {
        "descricao": "Você acabou trabalhando como músculos para algum bandido, sabendo que às vezes é preciso esmurrar alguém.",
        "itens": "Tatuagem ou outro adereço de sua gangue (+1 em Intimidação), uma arma simples corpo a corpo.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Luta", "Intimidação", "Confissão", "Poder de Combate (Escolha)"],
    },
    "Charlatão": {
        "descricao": "Você sempre teve talento para resolver problemas com conversa, usando palavras para vencer obstáculos.",
        "itens": "Estojo de disfarces, joia falsificada (valor aparente de T$ 100).",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Enganação", "Jogatina", "Alpinista Social", "Aparência Inofensiva", "Sortudo"],
    },
    "Circense": {
        "descricao": "Você treinou acrobacia, malabarismo, mágica ou outra forma de arte circense, útil em suas aventuras.",
        "itens": "Três bolas coloridas para malabarismo (+1 em Atuação).",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Acrobacia", "Atuação", "Reflexos", "Acrobático", "Torcida", "Truque de Mágica"],
    },
    "Criminoso": {
        "descricao": "Você foi um bandido durante boa parte da juventude, furtando bolsas, trapaceando ou aceitando contratos.",
        "itens": "Estojo de disfarces ou gazua.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Enganação", "Furtividade", "Ladinagem", "Punguista", "Venefício"],
    },
    "Curandeiro": {
        "descricao": "Você é treinado em curar com remédios e tratamentos naturais, sendo um ajudante de curandeiro ou tendo estudo formal.",
        "itens": "Bálsamo restaurador x2, maleta de medicamentos.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Cura", "Vontade", "Medicina", "Médico de Campo", "Venefício"],
    },
    "Eremita": {
        "descricao": "Você passou parte da vida isolado, buscando meditar, o que o tornou forte de corpo e espírito.",
        "itens": "Barraca, equipamento de viagem.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Misticismo", "Religião", "Sobrevivência", "Busca Interior", "Lobo Solitário"],
    },
    "Escravo": {
        "descricao": "Você já nasceu escravo ou foi capturado, mas encontrou uma chance de escapar ou foi libertado.",
        "itens": "Algemas, uma ferramenta pesada (maça).",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Atletismo", "Fortitude", "Furtividade", "Desejo de Liberdade", "Vitalidade"],
    },
    "Estudioso": {
        "descricao": "Longos anos de sua vida foram gastos em meio a livros e pergaminhos, em busca de desvendar segredos.",
        "itens": "Coleção de livros (+1 em Conhecimento, Guerra, Misticismo ou Nobreza, à sua escolha).",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Conhecimento", "Guerra", "Misticismo", "Aparência Inofensiva", "Palpite Fundamentado"],
    },
    "Fazendeiro": {
        "descricao": "Você trabalhou duro em campos e fazendas, cultivando a terra ou criando animais, vivendo em contato com a natureza.",
        "itens": "Carroça, uma ferramenta agrícola (lança), 10 rações de viagem, um animal não combativo.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Adestramento", "Cavalgar", "Ofício", "Sobrevivência", "Água no Feijão", "Ginete"],
    },
    "Forasteiro": {
        "descricao": "Você veio de longe e sua cultura nativa é quase ou totalmente desconhecida no Reinado, tornando-o uma figura exótica.",
        "itens": "Equipamento de viagem, instrumento musical exótico, traje estrangeiro.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Cavalgar", "Pilotagem", "Sobrevivência", "Cultura Exótica", "Lobo Solitário"],
    },
    "Gladiador": {
        "descricao": "Você se envolveu no mundo glamoroso de combates de arena, usando sua experiência em torneios para viver aventuras.",
        "itens": "Uma arma marcial ou exótica, um item sem valor recebido de um admirador.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Atuação", "Luta", "Atraente", "Pão e Circo", "Torcida", "Poder de Combate (Escolha)"],
    },
    "Guarda": {
        "descricao": "Você atuou como agente da lei, recebendo treino em investigação e combate antes de se tornar aventureiro.",
        "itens": "Apito, insígnia da milícia, uma arma marcial.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Investigação", "Luta", "Percepção", "Detetive", "Investigador", "Poder de Combate (Escolha)"],
    },
    "Herdeiro": {
        "descricao": "Você pertence a uma linhagem de nobres, magos ou outra atividade tradicional, recebendo treino e equipamento adequado.",
        "itens": "Um símbolo de sua herança, como um anel de sinete ou manto cerimonial.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Misticismo", "Nobreza", "Ofício", "Comandar", "Herança"],
    },
    "Herói Camponês": {
        "descricao": "Você era o campeão local, amado pelo povo, destinado a feitos maiores e com alguma arma há tempos guardada.",
        "itens": "Instrumentos de ofício ou uma arma simples, traje de plebeu.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Adestramento", "Ofício", "Coração Heroico", "Sortudo", "Surto Heroico", "Torcida"],
    },
    "Marujo": {
        "descricao": "Você foi tripulante em uma embarcação no Mar Negro ou no Rio dos Deuses, adquirindo aprendizado valioso.",
        "itens": "T$ 2d6 (seu último salário), corda.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Atletismo", "Jogatina", "Pilotagem", "Acrobático", "Passagem de Navio"],
    },
    "Mateiro": {
        "descricao": "Você aprendeu cedo a abater animais selvagens ou caçar, habituado a flechar cervos e colocar armadilhas.",
        "itens": "Arco curto, barraca, equipamento de viagem, 20 flechas.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Atletismo", "Furtividade", "Sobrevivência", "Lobo Solitário", "Sentidos Aguçados", "Vendedor de Carcaças"],
    },
    "Membro de Guilda": {
        "descricao": "Você foi membro atuante em uma grande guilda, que forneceu treinamento e equipamento necessário.",
        "itens": "Gazua ou instrumentos de ofício.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Diplomacia", "Enganação", "Misticismo", "Ofício", "Foco em Perícia", "Rede de Contatos"],
    },
    "Mercador": {
        "descricao": "Você atuou como comerciante, reunindo algum equipamento e dinheiro suficientes para começar carreira.",
        "itens": "Carroça, trobo, mercadorias para vender no valor de T$ 100.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Diplomacia", "Intuição", "Ofício", "Negociação", "Proficiência", "Sortudo"],
    },
    "Minerador": {
        "descricao": "Você mergulhou nas profundezas da terra atrás de metais e riquezas, adquirindo informação sobre túneis e masmorras.",
        "itens": "Gemas preciosas no valor de T$ 100, picareta.",
        "qtd_escolhas": 2,
        "pericias_fixas": ["Atletismo", "Fortitude", "Ofício"],
        "beneficios_lista": ["Ataque Poderoso", "Escavador", "Sentidos Aguçados"],
    },
    "Nômade": {
        "descricao": "Você nunca pertenceu a um só lugar, habituado às estradas e sem laços com nenhuma terra.",
        "itens": "Bordão, equipamento de viagem.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Cavalgar", "Pilotagem", "Sobrevivência", "Lobo Solitário", "Mochileiro", "Sentidos Aguçados"],
    },
    "Pivete": {
        "descricao": "Você era uma criança de rua, que aprendeu cedo a sobreviver em grandes cidades roubando ou cumprindo pequenas tarefas para bandidos.",
        "itens": "Gazua, traje de plebeu, um animal urbano.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Furtividade", "Iniciativa", "Ladinagem", "Acrobático", "Aparência Inofensiva", "Quebra-Galho"],
    },
    "Refugiado": {
        "descricao": "Você sobreviveu a guerras e tragédias, tornando-se um sobrevivente tenaz, acostumado a uma vida perigosa.",
        "itens": "Um item estrangeiro de até T$ 100.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Fortitude", "Reflexos", "Vontade", "Estoico", "Vontade de Ferro"],
    },
    "Seguidor": {
        "descricao": "Você viveu algum tempo na companhia de um herói, adquirindo aprendizado valioso antes de trilhar seu próprio caminho.",
        "itens": "Um item recebido de seu mestre de até T$ 100.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Adestramento", "Ofício", "Antigo Mestre", "Proficiência", "Surto Heroico"],
    },
    "Selvagem": {
        "descricao": "Você nasceu em uma tribo de bárbaros incultos ou foi criado por animais, sem contato com a civilização.",
        "itens": "Uma arma simples, um pequeno animal de estimação.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Percepção", "Reflexos", "Sobrevivência", "Lobo Solitário", "Vida Rústica", "Vitalidade"],
    },
    "Soldado": {
        "descricao": "Você se alistou como soldado em um grande exército, recebendo treinamento em combate e equipamento decente.",
        "itens": "Uma arma marcial, um uniforme militar, uma insígnia de seu exército.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Fortitude", "Guerra", "Luta", "Pontaria", "Influência Militar", "Poder de Combate (Escolha)"],
    },
    "Taverneiro": {
        "descricao": "Você foi dono, filho do dono ou empregado em algum lugar frequentado por aventureiros, ouvindo todas as grandes histórias.",
        "itens": "Rolo de macarrão ou martelo de carne (clava), uma panela, um avental, uma caneca e um pano sujo.",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Diplomacia", "Jogatina", "Ofício", "Gororoba", "Proficiência", "Vitalidade"],
    },
    "Trabalhador": {
        "descricao": "Você trabalhou braçalmente, transportando pedras ou pilhando cargas, tornando-se forte de corpo.",
        "itens": "Uma ferramenta pesada (maça ou lança, à sua escolha).",
        "qtd_escolhas": 2,
        "pericias_fixas": [],
        "beneficios_lista": ["Atletismo", "Fortitude", "Atlético", "Esforçado"],
    },
}

# --- FIM DO DADOS_ORIGENS.PY ---
